<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Sun May 17 03:26:41 UTC 2015

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/DERBY-4155/DERBY-4155.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[DERBY-4155] jdbcapi/XATest.java  doesn&apos;t seem to be running anywhere</title>
                <link>https://issues.apache.org/jira/browse/DERBY-4155</link>
                <project id="10594" key="DERBY">Derby</project>
                    <description></description>
                <environment>jdbcapi/XATest  does not seem to be included in any suite.  It currently fails in testMorph because a transaction is active when a connection is closed.  I think the error is correct and the test needs to be changed.&lt;br/&gt;
</environment>
        <key id="12422507">DERBY-4155</key>
            <summary>jdbcapi/XATest.java  doesn&apos;t seem to be running anywhere</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="4" iconUrl="https://issues.apache.org/jira/images/icons/priorities/minor.png">Minor</priority>
                        <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="mikem">Mike Matrigali</assignee>
                                    <reporter username="kmarsden">Kathey Marsden</reporter>
                        <labels>
                    </labels>
                <created>Thu, 9 Apr 2009 20:26:05 +0100</created>
                <updated>Wed, 12 Jan 2011 22:24:24 +0000</updated>
                            <resolved>Sat, 10 Jul 2010 00:10:26 +0100</resolved>
                                    <version>10.5.1.1</version>
                    <version>10.6.1.0</version>
                                    <fixVersion>10.3.3.1</fixVersion>
                    <fixVersion>10.5.3.0</fixVersion>
                    <fixVersion>10.6.1.0</fixVersion>
                                    <component>Test</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>0</watches>
                                                                <comments>
                            <comment id="12698379" author="kristwaa" created="Mon, 13 Apr 2009 13:12:29 +0100"  >&lt;p&gt;Added a link to &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-3998&quot; title=&quot;Make sure all JUnit tests are run as part of a suite&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-3998&quot;&gt;DERBY-3998&lt;/a&gt;, which contains some more information about tests not being run.&lt;/p&gt;</comment>
                            <comment id="12729793" author="kmarsden" created="Fri, 10 Jul 2009 20:43:55 +0100"  >&lt;p&gt;This test would sometimes hang with &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4053&quot; title=&quot;Network Server&amp;#39;s failure to rollback local transactions on shutdown can cause  hang on startup with message java.net.BindException: Address already in use: NET_Bind in derby.log &quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4053&quot;&gt;&lt;del&gt;DERBY-4053&lt;/del&gt;&lt;/a&gt; symptoms so cannot be enabled until that is fixed.&lt;/p&gt;</comment>
                            <comment id="12731032" author="kmarsden" created="Tue, 14 Jul 2009 19:37:57 +0100"  >&lt;p&gt;After Mamta&apos;s fix for &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4053&quot; title=&quot;Network Server&amp;#39;s failure to rollback local transactions on shutdown can cause  hang on startup with message java.net.BindException: Address already in use: NET_Bind in derby.log &quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4053&quot;&gt;&lt;del&gt;DERBY-4053&lt;/del&gt;&lt;/a&gt; I tried enable this test and ran suites.All three times.&lt;br/&gt;
First time I got well past XATest and my machine froze up in teh replication tests and I had to reboot.&lt;/p&gt;

&lt;p&gt;Second  run I hit &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4053&quot; title=&quot;Network Server&amp;#39;s failure to rollback local transactions on shutdown can cause  hang on startup with message java.net.BindException: Address already in use: NET_Bind in derby.log &quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4053&quot;&gt;&lt;del&gt;DERBY-4053&lt;/del&gt;&lt;/a&gt; (even with the fix) a&lt;/p&gt;

&lt;p&gt;Third run I hit a different problem:&lt;br/&gt;
junit.framework.AssertionFailedError: Column value mismatch @ column &apos;STATUS&apos;, row 1:&lt;br/&gt;
    Expected: &amp;gt;PREPARED&amp;lt;&lt;br/&gt;
    Found:    &amp;gt;IDLE&amp;lt;&lt;br/&gt;
        at junit.framework.Assert.fail(Assert.java:47)&lt;br/&gt;
        at org.apache.derbyTesting.junit.JDBC.assertRowInResultSet(JDBC.java:1095)&lt;br/&gt;
        at org.apache.derbyTesting.junit.JDBC.assertRowInResultSet(JDBC.java:1007)&lt;br/&gt;
        at org.apache.derbyTesting.junit.JDBC.assertFullResultSet(JDBC.java:895)&lt;br/&gt;
        at org.apache.derbyTesting.junit.JDBC.assertFullResultSet(JDBC.java:833)&lt;br/&gt;
        at org.apache.derbyTesting.junit.JDBC.assertFullResultSet(JDBC.java:791)&lt;br/&gt;
        at org.apache.derbyTesting.junit.XATestUtil.checkXATransactionView(XATestUtil.java:82)&lt;br/&gt;
        at org.apache.derbyTesting.functionTests.tests.jdbcapi.XATest.testMorph(XATest.java:547)&lt;br/&gt;
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)&lt;br/&gt;
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
        at java.lang.reflect.Method.invoke(Method.java:599)&lt;br/&gt;
        at junit.framework.TestCase.runTest(TestCase.java:154)&lt;br/&gt;
        at junit.framework.TestCase.runBare(TestCase.java:127)&lt;br/&gt;
        at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:109)&lt;br/&gt;
        at junit.framework.TestResult$1.protect(TestResult.java:106)&lt;br/&gt;
        at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
        at junit.framework.TestResult.run(TestResult.java:103)&lt;br/&gt;
        at junit.framework.TestCase.run(TestCase.java:118)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)&lt;br/&gt;
        at junit.extensions.TestSetup$1.protect(TestSetup.java:19)&lt;br/&gt;
        at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
        at junit.extensions.TestSetup.run(TestSetup.java:23)&lt;br/&gt;
        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)&lt;br/&gt;
        at junit.extensions.TestSetup$1.protect(TestSetup.java:19)&lt;br/&gt;
        at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
        at junit.extensions.TestSetup.run(TestSetup.java:23)&lt;br/&gt;
        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)&lt;br/&gt;
        at junit.extensions.TestSetup$1.protect(TestSetup.java:19)&lt;br/&gt;
        at junit.framework.TestResult.runProtected(TestResult.java:124)&lt;br/&gt;
        at junit.extensions.TestSetup.run(TestSetup.java:23)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.framework.TestSuite.runTest(TestSuite.java:208)&lt;br/&gt;
        at junit.framework.TestSuite.run(TestSuite.java:203)&lt;br/&gt;
        at junit.textui.TestRunner.doRun(TestRunner.java:116)&lt;br/&gt;
        at junit.textui.TestRunner.start(TestRunner.java:172)&lt;br/&gt;
        at junit.textui.TestRunner.main(TestRunner.java:138)&lt;/p&gt;

&lt;p&gt;This failure caused subsequent tests to run very slowly because of lock timeouts in CleanDatabaseSetup because there was a statement left prepared.  I am going to try again with just the jdbcapi suite.&lt;/p&gt;
</comment>
                            <comment id="12731086" author="kmarsden" created="Tue, 14 Jul 2009 20:56:10 +0100"  >&lt;p&gt;I changed the test to check for an unordered result set to avoid the PREPARED vs IDLE error above and get fairly consistently this issue on network shutdown running the test standalone if I use the derby-4053_diag_diff.txt patch.  I am guessing this error is the one that caused &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4053&quot; title=&quot;Network Server&amp;#39;s failure to rollback local transactions on shutdown can cause  hang on startup with message java.net.BindException: Address already in use: NET_Bind in derby.log &quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4053&quot;&gt;&lt;del&gt;DERBY-4053&lt;/del&gt;&lt;/a&gt; in the second run.&lt;/p&gt;

&lt;p&gt;I am guessing this is some kind of embedded bug regarding closing BrokeredStatements when the referenced table had been dropped.  I will try to get  a stand-alone repro for that.&lt;/p&gt;


&lt;p&gt;testDerby966 used 125 ms java.sql.SQLSyntaxErrorException: Table/View &apos;APP.FOO&apos; does not exist.&lt;br/&gt;
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:91)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:201)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:391)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2201)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.&amp;lt;init&amp;gt;(EmbedPreparedStatement.java:147)&lt;br/&gt;
        at org.apache.derby.jdbc.Driver40.newEmbedPreparedStatement(Driver40.java:105)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(EmbedConnection.java:1542)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(EmbedConnection.java:1423)&lt;br/&gt;
        at org.apache.derby.iapi.jdbc.BrokeredPreparedStatement30.createDuplicateStatement(BrokeredPreparedStatement30.j&lt;br/&gt;
ava:56)&lt;br/&gt;
        at org.apache.derby.jdbc.XAStatementControl.getRealPreparedStatement(XAStatementControl.java:143)&lt;br/&gt;
        at org.apache.derby.iapi.jdbc.BrokeredPreparedStatement.getPreparedStatement(BrokeredPreparedStatement.java:526)&lt;/p&gt;

&lt;p&gt;        at org.apache.derby.iapi.jdbc.BrokeredPreparedStatement.getStatement(BrokeredPreparedStatement.java:533)&lt;br/&gt;
        at org.apache.derby.iapi.jdbc.BrokeredStatement.close(BrokeredStatement.java:130)&lt;br/&gt;
        at org.apache.derby.impl.drda.DRDAStatement.close(DRDAStatement.java:1027)&lt;br/&gt;
        at org.apache.derby.impl.drda.Database.close(Database.java:352)&lt;br/&gt;
        at org.apache.derby.impl.drda.Session.close(Session.java:115)&lt;br/&gt;
        at org.apache.derby.impl.drda.NetworkServerControlImpl.blockingStart(NetworkServerControlImpl.java:826)&lt;br/&gt;
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)&lt;br/&gt;
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
        at java.lang.reflect.Method.invoke(Method.java:599)&lt;br/&gt;
        at org.apache.derby.iapi.jdbc.DRDAServerStarter.run(DRDAServerStarter.java:236)&lt;br/&gt;
        at java.lang.Thread.run(Thread.java:735)&lt;br/&gt;
Caused by: java.sql.SQLException: Table/View &apos;APP.FOO&apos; does not exist.&lt;br/&gt;
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:11&lt;br/&gt;
9)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)&lt;br/&gt;
        ... 24 more&lt;br/&gt;
Caused by: ERROR 42X05: Table/View &apos;APP.FOO&apos; does not exist.&lt;br/&gt;
        at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:286)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(FromBaseTable.java:2463)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(FromBaseTable.java:2183)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.FromList.bindTables(FromList.java:310)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(SelectNode.java:390)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(DMLStatementNode.java:199)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(DMLStatementNode.java:137)&lt;br/&gt;
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(CursorNode.java:245)&lt;br/&gt;
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(GenericStatement.java:316)&lt;br/&gt;
        at org.apache.derby.impl.sql.GenericStatement.prepare(GenericStatement.java:88)&lt;br/&gt;
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(GenericLanguageConne&lt;br/&gt;
ctionContext.java:822)&lt;br/&gt;
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.&amp;lt;init&amp;gt;(EmbedPreparedStatement.java:129)&lt;br/&gt;
        ... 18 more&lt;/p&gt;
</comment>
                            <comment id="12737678" author="espinha" created="Fri, 31 Jul 2009 20:43:20 +0100"  >&lt;p&gt;I&apos;m submitting a patch to this issue. This patch adds the XATest to the respective suite and adds two fixtures to test &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4310&quot; title=&quot;Closing a prepared statement with an embedded   XAConnection can cause the statement to be reprepared and errors related to missing dependencies. This can interfere with network server closeSession()&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4310&quot;&gt;&lt;del&gt;DERBY-4310&lt;/del&gt;&lt;/a&gt;. I&apos;ll be adding another patch to the other issue that fixes the behavior described on the comments.&lt;/p&gt;</comment>
                            <comment id="12738553" author="kmarsden" created="Mon, 3 Aug 2009 21:19:29 +0100"  >&lt;p&gt;Resolving for 10.6. If backported &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4310&quot; title=&quot;Closing a prepared statement with an embedded   XAConnection can cause the statement to be reprepared and errors related to missing dependencies. This can interfere with network server closeSession()&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4310&quot;&gt;&lt;del&gt;DERBY-4310&lt;/del&gt;&lt;/a&gt; needs to be backported as well.&lt;/p&gt;</comment>
                            <comment id="12741330" author="kmarsden" created="Mon, 10 Aug 2009 15:06:10 +0100"  >&lt;p&gt;Now that XATest has been enabled we have increased exposure to &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4158&quot; title=&quot;If XA tests fail after the prepare of a transaction, subsequent tests may be affected&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4158&quot;&gt;DERBY-4158&lt;/a&gt;. If there are any more backports of &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4310&quot; title=&quot;Closing a prepared statement with an embedded   XAConnection can cause the statement to be reprepared and errors related to missing dependencies. This can interfere with network server closeSession()&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4310&quot;&gt;&lt;del&gt;DERBY-4310&lt;/del&gt;&lt;/a&gt; and &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4155&quot; title=&quot;jdbcapi/XATest.java  doesn&amp;#39;t seem to be running anywhere&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4155&quot;&gt;&lt;del&gt;DERBY-4155&lt;/del&gt;&lt;/a&gt;, All changes need to be backported to void slow tests and other issues if any of the XATest fixtures fail.&lt;/p&gt;</comment>
                            <comment id="12741371" author="rhillegas" created="Mon, 10 Aug 2009 16:33:07 +0100"  >&lt;p&gt;This fix appears to have been merged to the 10.5 branch in time to get onto the next release train so I am marking this as fixed in 10.5.3.&lt;/p&gt;</comment>
                            <comment id="12741379" author="espinha" created="Mon, 10 Aug 2009 16:38:56 +0100"  >&lt;p&gt;Indeed, this issue was merged to 10.5 on revision 802397.&lt;/p&gt;

&lt;p&gt;I&apos;m closing the issue as for now I don&apos;t think we will be merging it to other branches.&lt;/p&gt;</comment>
                            <comment id="12886836" author="mikem" created="Fri, 9 Jul 2010 20:07:05 +0100"  >&lt;p&gt;reopening issue to look at backporting it to 10.3.  I am trying to backport fix for &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4731&quot; title=&quot;XA two phase commit with active  GLOBAL TEMPORARY TABLE causes  An internal error identified by RawStore module&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4731&quot;&gt;&lt;del&gt;DERBY-4731&lt;/del&gt;&lt;/a&gt;&lt;br/&gt;
but this is blocking my testing of it there.&lt;/p&gt;</comment>
                            <comment id="12886939" author="mikem" created="Sat, 10 Jul 2010 00:10:26 +0100"  >&lt;p&gt;I backported the test changes associated with this issue to 10.3.  &lt;/p&gt;

&lt;p&gt;backporting the current state of XATest.java and XAtestUtil.java from trunk&lt;br/&gt;
to 10.3 branch. Disabled the test for &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4731&quot; title=&quot;XA two phase commit with active  GLOBAL TEMPORARY TABLE causes  An internal error identified by RawStore module&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4731&quot;&gt;&lt;del&gt;DERBY-4731&lt;/del&gt;&lt;/a&gt;, to be enabled later when&lt;br/&gt;
that is backported. It looks like all of the changes for the rest of this&lt;br/&gt;
issue were already backported to 10.3 as part of the backport of &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4310&quot; title=&quot;Closing a prepared statement with an embedded   XAConnection can cause the statement to be reprepared and errors related to missing dependencies. This can interfere with network server closeSession()&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4310&quot;&gt;&lt;del&gt;DERBY-4310&lt;/del&gt;&lt;/a&gt;. &lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10032">
                    <name>Blocker</name>
                                            <outwardlinks description="blocks">
                                        <issuelink>
            <issuekey id="12414620">DERBY-4053</issuekey>
        </issuelink>
                            </outwardlinks>
                                                                <inwardlinks description="is blocked by">
                                        <issuelink>
            <issuekey id="12430639">DERBY-4310</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                            <issuelinktype id="10030">
                    <name>Reference</name>
                                            <outwardlinks description="relates to">
                                        <issuelink>
            <issuekey id="12422612">DERBY-4158</issuekey>
        </issuelink>
            <issuelink>
            <issuekey id="12411413">DERBY-3998</issuekey>
        </issuelink>
                            </outwardlinks>
                                                        </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12415164" name="DERBY-4155-XATest.patch" size="24044" author="espinha" created="Fri, 31 Jul 2009 20:43:20 +0100"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>1.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>Date of First Response</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Mon, 13 Apr 2009 12:12:29 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                    <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>24067</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2|hy0o0v:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>37710</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                        <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                            </customfields>
    </item>
</channel>
</rss>