<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Sun May 17 03:34:39 UTC 2015

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/DERBY-5158/DERBY-5158.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[DERBY-5158] Incomprehensible error message on client if attempting rollback after database has been shut down.</title>
                <link>https://issues.apache.org/jira/browse/DERBY-5158</link>
                <project id="10594" key="DERBY">Derby</project>
                    <description>&lt;p&gt;Cf the attached repro: when performing the rollback after the database has been shutdown, we see this error:&lt;/p&gt;

&lt;p&gt;There was 1 error:&lt;br/&gt;
1) testShutdown(org.apache.derbyTesting.functionTests.tests.store.Foo)java.sql.SQLNonTransientConnectionException: Network protocol exception: actual code point, 4,692, does not match expected code point, 9,224.  The connection has been terminated.&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:358)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.rollback(Connection.java:659)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseJDBCTestCase.rollback(BaseJDBCTestCase.java:387)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.store.Foo.testShutdown(Foo.java:100)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
Caused by: org.apache.derby.client.am.DisconnectException: Network protocol exception: actual code point, 4,692, does not match expected code point, 9,224.  The connection has been terminated.&lt;br/&gt;
	at org.apache.derby.client.net.Reply.parseLengthAndMatchCodePoint(Reply.java:1075)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseSQLCARD(NetConnectionReply.java:2572)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRDBRLLBCKreply(NetConnectionReply.java:219)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.readLocalRollback(NetConnectionReply.java:141)&lt;br/&gt;
	at org.apache.derby.client.net.ConnectionReply.readLocalRollback(ConnectionReply.java:48)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.readLocalRollback_(NetConnection.java:1515)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.readRollback(Connection.java:707)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.flowRollback(Connection.java:690)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.rollback(Connection.java:655)&lt;br/&gt;
	... 29 more&lt;/p&gt;</description>
                <environment></environment>
        <key id="12502601">DERBY-5158</key>
            <summary>Incomprehensible error message on client if attempting rollback after database has been shut down.</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="4" iconUrl="https://issues.apache.org/jira/images/icons/priorities/minor.png">Minor</priority>
                        <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="dagw">Dag H. Wanvik</assignee>
                                    <reporter username="dagw">Dag H. Wanvik</reporter>
                        <labels>
                    </labels>
                <created>Mon, 28 Mar 2011 17:42:02 +0100</created>
                <updated>Tue, 25 Oct 2011 18:09:30 +0100</updated>
                            <resolved>Tue, 23 Aug 2011 01:51:52 +0100</resolved>
                                                    <fixVersion>10.8.2.2</fixVersion>
                    <fixVersion>10.9.1.0</fixVersion>
                                        <due></due>
                            <votes>0</votes>
                                    <watches>0</watches>
                                                                <comments>
                            <comment id="13012130" author="dagw" created="Mon, 28 Mar 2011 17:49:13 +0100"  >&lt;p&gt;In contrast, if we attempt to execute a query (rather than a rollback), we see the more understandable error stack trace whose ultimate cause is given as &quot;No current connection&quot;:&lt;/p&gt;

&lt;p&gt;1) testShutdown(org.apache.derbyTesting.functionTests.tests.store.Foo)java.sql.SQLNonTransientConnectionException: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:358)&lt;br/&gt;
	at org.apache.derby.client.am.Statement.executeQuery(Statement.java:486)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.store.Foo.testShutdown(Foo.java:102)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
Caused by: org.apache.derby.client.am.DisconnectException: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseCMDCHKRM(NetConnectionReply.java:882)&lt;br/&gt;
	at org.apache.derby.client.net.NetStatementReply.parsePrepareError(NetStatementReply.java:550)&lt;br/&gt;
	at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(NetStatementReply.java:144)&lt;br/&gt;
	at org.apache.derby.client.net.NetStatementReply.readPrepareDescribeOutput(NetStatementReply.java:53)&lt;br/&gt;
	at org.apache.derby.client.net.StatementReply.readPrepareDescribeOutput(StatementReply.java:40)&lt;br/&gt;
	at org.apache.derby.client.net.NetStatement.readPrepareDescribeOutput_(NetStatement.java:138)&lt;br/&gt;
	at org.apache.derby.client.am.Statement.readPrepareDescribeOutput(Statement.java:1443)&lt;br/&gt;
	at org.apache.derby.client.am.Statement.flowExecute(Statement.java:2117)&lt;br/&gt;
	at org.apache.derby.client.am.Statement.executeQueryX(Statement.java:492)&lt;br/&gt;
	at org.apache.derby.client.am.Statement.executeQuery(Statement.java:477)&lt;br/&gt;
	... 28 more&lt;br/&gt;
Caused by: java.lang.Exception: No current connection.&lt;/p&gt;</comment>
                            <comment id="13012138" author="dagw" created="Mon, 28 Mar 2011 18:02:23 +0100"  >&lt;p&gt;The problem seems to be the following:&lt;/p&gt;

&lt;p&gt;In DRDAConnThread#processCommands we have this code for rollback:&lt;/p&gt;

&lt;p&gt;     case CodePoint.RDBCMM:&lt;br/&gt;
             try &lt;/p&gt;
{..}
&lt;p&gt;             catch (SQLException e)&lt;/p&gt;
             {
                     writer.clearDSSesBackToMark(writerMark);
                     // Even in case of error, we have to write the ENDUOWRM.
                     writeENDUOWRM(COMMIT);
                     writeSQLCARDs(e, 0);
                     errorInChain(e);
             }

&lt;p&gt;i.e. we send an ENDUOWRM, then the writeSQLCARDs will send a CMDCHKRM (severe error), then&lt;br/&gt;
the SQLCARD.&lt;/p&gt;

&lt;p&gt;However, on the client side, we see this code to handle reply for rollback:&lt;/p&gt;

&lt;p&gt;    private void parseRDBRLLBCKreply(ConnectionCallbackInterface connection) &lt;br/&gt;
        throws DisconnectException {&lt;br/&gt;
        int peekCP = parseTypdefsOrMgrlvlovrs();&lt;br/&gt;
        if (peekCP != CodePoint.ENDUOWRM) &lt;/p&gt;
{  &amp;lt;---------------- Note!
            parseRollbackError();
            return;
        }

&lt;p&gt;        parseENDUOWRM(connection);&lt;br/&gt;
        peekCP = parseTypdefsOrMgrlvlovrs();&lt;/p&gt;

&lt;p&gt;        NetSqlca netSqlca = parseSQLCARD(null);&lt;br/&gt;
        connection.completeSqlca(netSqlca);&lt;br/&gt;
    }&lt;/p&gt;

&lt;p&gt;that is, parseRollbackError is only executed iff ENDUOWRM is not&lt;br/&gt;
returned. But we just saw that the server side sent a ENDUOWRM even&lt;br/&gt;
under an error condition. So, the client will happily&lt;br/&gt;
parseENDUOWRM and then expect SQLCARD when there is actually a CMDCHKRM&lt;br/&gt;
waiting. hence the code point error. I am not sure which side is&lt;br/&gt;
correct here, but maybe you DRDA experts can help out &lt;img class=&quot;emoticon&quot; src=&quot;https://issues.apache.org/jira/images/icons/emoticons/wink.gif&quot; height=&quot;16&quot; width=&quot;16&quot; align=&quot;absmiddle&quot; alt=&quot;&quot; border=&quot;0&quot;/&gt;&lt;/p&gt;</comment>
                            <comment id="13012139" author="dagw" created="Mon, 28 Mar 2011 18:05:23 +0100"  >&lt;p&gt;Btw, code point 4692 (0x1254) is CMDCHKRM,  9224 (0x2408) is SQLCARD.&lt;/p&gt;</comment>
                            <comment id="13012144" author="dagw" created="Mon, 28 Mar 2011 18:12:42 +0100"  >&lt;p&gt;A commit in the same location as the rollback, does not throw.&lt;/p&gt;</comment>
                            <comment id="13012745" author="dagw" created="Tue, 29 Mar 2011 23:14:36 +0100"  >&lt;p&gt;The reason the commit does not throw is that the repro did not switch off autocommit, so the commit is never sent to the server (&lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4653&quot; title=&quot;Avoid unnecessary round-trip for commit  in the client driver&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4653&quot;&gt;&lt;del&gt;DERBY-4653&lt;/del&gt;&lt;/a&gt; optimization). The rollback is still flowed, cf. &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4687&quot; title=&quot;Avoid unnecessary round-trip for rollback in the client driver&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4687&quot;&gt;DERBY-4687&lt;/a&gt;.&lt;/p&gt;</comment>
                            <comment id="13012751" author="dagw" created="Tue, 29 Mar 2011 23:33:20 +0100"  >&lt;p&gt;By adding setAUtoCommit(false) in Derby5158Repro#setUp, we see the issue also for commit.&lt;/p&gt;</comment>
                            <comment id="13015461" author="dagw" created="Mon, 4 Apr 2011 16:23:11 +0100"  >&lt;p&gt;Attaching a patch, &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5158&quot; title=&quot;Incomprehensible error message on client if attempting rollback after database has been shut down.&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5158&quot;&gt;&lt;del&gt;DERBY-5158&lt;/del&gt;&lt;/a&gt;a, which corrects the protocol code on the client side to cater for ENDUOWRM even in the error case (as sent by the server). Looking at the DRDA standard, I didn&apos;t quite manage to satisfy myself that this is the correct behavior, but almost: section 7.5 Commit/Rollback processing, where CR2 says:&lt;/p&gt;

&lt;p&gt;&quot;Application servers using remote unit of work protocols and application servers using distributed unit of work but not protected by a sync point manager must inform the application requester when the current unit of work at the application server ends as a result of a commit or rollback request by an application or application requester request. This information is returned in the RPYDSS, containing the ENDUOWRM reply message.&quot;&lt;/p&gt;

&lt;p&gt;So, does the above apply when an error happens (the database has already been shut down, so no connection can be established)? In a way, the &quot;remote unit of work&quot; is definitely ended, so...&lt;/p&gt;

&lt;p&gt;Note that the (new) error stack trace is still different than with the embedded driver, since there the 08003 will be directly reported as the error (not wrapped in 06006 as shown below for the client side). &lt;/p&gt;

&lt;p&gt;I added a new test, Derby5158Test, not being sure where to put this new test case (I didn&apos;t find any specific tests for commit/rollback), if you know a better placement for it, let me know! I could always put it in ShutdownDatabaseTest, I guess..&lt;/p&gt;

&lt;p&gt;Running regressions.&lt;/p&gt;

&lt;p&gt;With this new code, the following error stack dump can be seen on the client side, which shows that the underlyinc cause of the error is 08003. &quot;No current connection&quot;.&lt;/p&gt;

&lt;p&gt;java.sql.SQLNonTransientConnectionException: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)&lt;br/&gt;
	at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)&lt;br/&gt;
	at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:358)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.rollback(Connection.java:659)&lt;br/&gt;
	at org.apache.derbyTesting.functionTests.tests.jdbcapi.Derby5158Test.testShutdown(Derby5158Test.java:71)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
	at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)&lt;br/&gt;
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)&lt;br/&gt;
	at junit.extensions.TestSetup$1.protect(TestSetup.java:21)&lt;br/&gt;
	at junit.extensions.TestSetup.run(TestSetup.java:25)&lt;br/&gt;
Caused by: org.apache.derby.client.am.DisconnectException: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseCMDCHKRM(NetConnectionReply.java:880)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRollbackError(NetConnectionReply.java:359)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.parseRDBRLLBCKreply(NetConnectionReply.java:216)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnectionReply.readLocalRollback(NetConnectionReply.java:141)&lt;br/&gt;
	at org.apache.derby.client.net.ConnectionReply.readLocalRollback(ConnectionReply.java:48)&lt;br/&gt;
	at org.apache.derby.client.net.NetConnection.readLocalRollback_(NetConnection.java:1515)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.readRollback(Connection.java:707)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.flowRollback(Connection.java:690)&lt;br/&gt;
	at org.apache.derby.client.am.Connection.rollback(Connection.java:655)&lt;br/&gt;
	... 28 more&lt;br/&gt;
Caused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: 08003, SQLERRMC: No current connection.&lt;br/&gt;
	... 37 more&lt;/p&gt;</comment>
                            <comment id="13015723" author="bryanpendleton" created="Tue, 5 Apr 2011 03:05:48 +0100"  >&lt;p&gt;I find your reading of the documents reasonable, and the behavior of the system with&lt;br/&gt;
your change is clearly superior to the prior behavior. Having &quot;No current connection&quot;&lt;br/&gt;
appear in the stack trace (which your change does) should provide adequate information&lt;br/&gt;
for a motivated developer to figure out that they&apos;ve attempted a rollback but are&lt;br/&gt;
not currently connected to the database, which seems like the basic goal of your fix.&lt;/p&gt;

&lt;p&gt;So, +1 from me!&lt;/p&gt;</comment>
                            <comment id="13015899" author="dagw" created="Tue, 5 Apr 2011 13:55:32 +0100"  >&lt;p&gt;Thanks, Bryan! Yes, that was my goal indeed. Regressions ran ok.&lt;/p&gt;</comment>
                            <comment id="13016181" author="dagw" created="Wed, 6 Apr 2011 00:34:24 +0100"  >&lt;p&gt;Uploading a new version of the patch, which improves the test a bit: we now make sure to do some work before closing down the database, since otherwise the client short circuits the commit (if it knows nothing happened yet on this connection). Rollback does not do this, cf. &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-4653&quot; title=&quot;Avoid unnecessary round-trip for commit  in the client driver&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-4653&quot;&gt;&lt;del&gt;DERBY-4653&lt;/del&gt;&lt;/a&gt;.(I did not notice this optimization in the first version, but saw it when instrumenting it for verification.)&lt;/p&gt;

&lt;p&gt;I did not move the test into ShutdownDatabaseTest, because that test does not yet run with client/server due to &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-2477&quot; title=&quot;shutting down the database causes some issues for the network server&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-2477&quot;&gt;DERBY-2477&lt;/a&gt;. Linked this issue to that also.&lt;/p&gt;</comment>
                            <comment id="13016787" author="dagw" created="Thu, 7 Apr 2011 10:51:42 +0100"  >&lt;p&gt;Re-ran suites.All ok with version &quot;b&quot;, modulo a new instance of &lt;a href=&quot;https://issues.apache.org/jira/browse/DERBY-5003&quot; title=&quot;NPE in ReplicationRun_Local_3_p5 when stopping slave after purposefully crashing master&quot; class=&quot;issue-link&quot; data-issue-key=&quot;DERBY-5003&quot;&gt;DERBY-5003&lt;/a&gt;.&lt;/p&gt;</comment>
                            <comment id="13016790" author="dagw" created="Thu, 7 Apr 2011 11:00:42 +0100"  >&lt;p&gt;Committed as svn 1089795, resolving.&lt;/p&gt;</comment>
                            <comment id="13086547" author="kmarsden" created="Wed, 17 Aug 2011 20:50:20 +0100"  >&lt;p&gt;Should we consider this for backport?&lt;/p&gt;</comment>
                            <comment id="13086683" author="dagw" created="Thu, 18 Aug 2011 00:39:12 +0100"  >&lt;p&gt;I think it would be fine if you think it is important enough.&lt;/p&gt;</comment>
                            <comment id="13089119" author="myrna" created="Mon, 22 Aug 2011 23:58:09 +0100"  >&lt;p&gt;Reopen for backport to 10.8&lt;/p&gt;</comment>
                            <comment id="13089190" author="myrna" created="Tue, 23 Aug 2011 01:51:52 +0100"  >&lt;p&gt;backported the fix to 10.8 with revision 1160516.&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10030">
                    <name>Reference</name>
                                            <outwardlinks description="relates to">
                                        <issuelink>
            <issuekey id="12365514">DERBY-2477</issuekey>
        </issuelink>
                            </outwardlinks>
                                                        </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12475381" name="DERBY-5158a.diff" size="6489" author="dagw" created="Mon, 4 Apr 2011 16:23:11 +0100"/>
                            <attachment id="12475382" name="DERBY-5158a.stat" size="249" author="dagw" created="Mon, 4 Apr 2011 16:23:11 +0100"/>
                            <attachment id="12475543" name="DERBY-5158b.diff" size="7399" author="dagw" created="Wed, 6 Apr 2011 00:34:24 +0100"/>
                            <attachment id="12475544" name="DERBY-5158b.stat" size="249" author="dagw" created="Wed, 6 Apr 2011 00:34:24 +0100"/>
                            <attachment id="12474788" name="Derby5158Repro.java" size="3002" author="dagw" created="Mon, 28 Mar 2011 17:53:09 +0100"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>5.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                        <customfield id="customfield_12310200" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Bug behavior facts</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10363"><![CDATA[Embedded/Client difference]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                    <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>Date of First Response</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Tue, 5 Apr 2011 02:05:48 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                    <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>24680</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                        <customfield id="customfield_12310090" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Issue &amp; fix info</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10424"><![CDATA[Repro attached]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2|hy0f0f:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>36250</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                        <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                            </customfields>
    </item>
</channel>
</rss>